"""Sync schema with models for PostgreSQL

Revision ID: 5f761693b7cb
Revises: 9eb4a0c2be96
Create Date: 2026-01-23 21:40:28.522306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f761693b7cb'
down_revision: Union[str, Sequence[str], None] = '9eb4a0c2be96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_executions', sa.Column('refined_outputs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_executions', 'refined_outputs')
    # ### end Alembic commands ###
