"""Add chunk_metadata to knowledge chunks

Revision ID: d8cffc20c366
Revises: 5f761693b7cb
Create Date: 2026-01-23 23:10:48.778663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8cffc20c366'
down_revision: Union[str, Sequence[str], None] = '5f761693b7cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creator_studio_knowledge_chunks', sa.Column('chunk_metadata', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creator_studio_knowledge_chunks', 'chunk_metadata')
    # ### end Alembic commands ###
