"""add_human_in_loop_fields

Revision ID: e938e5d440c1
Revises: 9d2e0b4a7c3d
Create Date: 2026-01-10 23:36:11.258031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e938e5d440c1'
down_revision: Union[str, Sequence[str], None] = '9d2e0b4a7c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_executions', sa.Column('review_status', sa.Enum('none', 'pending', 'in_progress', 'completed', 'rejected', name='reviewstatus'), nullable=False, server_default='none'))
    op.add_column('agent_executions', sa.Column('review_request_note', sa.Text(), nullable=True))
    op.add_column('agent_executions', sa.Column('review_response_note', sa.Text(), nullable=True))
    op.add_column('agent_executions', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('agents', sa.Column('allow_reviews', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('review_cost', sa.Integer(), nullable=False, server_default='5'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'review_cost')
    op.drop_column('agents', 'allow_reviews')
    op.drop_column('agent_executions', 'reviewed_at')
    op.drop_column('agent_executions', 'review_response_note')
    op.drop_column('agent_executions', 'review_request_note')
    op.drop_column('agent_executions', 'review_status')
    # ### end Alembic commands ###
